name: GitHub Metrics (Everforest)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: nphuong302
          template: classic

          # ===== Minimal base =====
          base: header

          config_timezone: Asia/Ho_Chi_Minh
          config_theme: dark
          config_padding: 16
          config_border_radius: 12

          # ===== Everforest palette =====
          config_colors: |
            background: 2d353b   # bg0
            foreground: d3c6aa   # fg
            highlight: a7c080    # green chủ đạo
            accent: dbbc7f       # yellow vintage

          # ===== Languages only =====
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_limit: 5
          plugin_languages_sections: most-used
